version: "3.8"
services:
  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - app.env
    depends_on:
      - db
    volumes:
      - ./app-logs:/app/logs
  db:
    image: postgres
    restart: always
    env_file:
      - db.env
    ports:
      - "8090:5432"
    volumes:
      - ./src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/1.sql
      - ./src/main/resources/db/populate.sql:/docker-entrypoint-initdb.d/2.sql