version: "3.8"
services:
  db:
    image: postgres
    restart: always
    env_file:
      - db.env
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/1_init.sql
      - ./src/main/resources/db/populate.sql:/docker-entrypoint-initdb.d/2_populate.sql
  app:
    build: .
    restart: always
    ports:
      - "80:8080"
    env_file:
      - app.env
    depends_on:
      - db
    volumes:
      - ./app-logs:/app/logs